import * as monaco from 'monaco-editor';

// Markdown 语法高亮规则
function register_markdown_tokens() {
  monaco.languages.setMonarchTokensProvider('markdown', {
    defaultToken: '',
    includeLF: true,

    escapes: /\\(?:[btnfr\\"']|[0-7]{1,3}|x[0-9A-Fa-f]{1,4}|u[0-9A-Fa-f]{4})/,

    // 代码块内通用的关键词
    code_keywords: [
      'if',
      'else',
      'elif',
      'for',
      'while',
      'do',
      'switch',
      'case',
      'match',
      'break',
      'continue',
      'return',
      'throw',
      'try',
      'catch',
      'finally',
      'yield',
      'await',
      'async',
      'defer',
      'fallthrough',
      'import',
      'export',
      'from',
      'as',
      'default',
      'extends',
      'implements',
      'interface',
      'class',
      'function',
      'def',
      'fn',
      'fun',
      'func',
      'var',
      'let',
      'const',
      'val',
      'mut',
      'static',
      'private',
      'protected',
      'public',
      'readonly',
      'abstract',
      'override',
      'virtual',
      'sealed',
      'enum',
      'type',
      'module',
      'namespace',
      'declare',
      'package',
      'require',
      'include',
      'use',
      'mod',
      'extern',
      'crate',
      'pub',
      'self',
      'super',
      'this',
      'base',
      'new',
      'delete',
      'typeof',
      'instanceof',
      'void',
      'in',
      'of',
      'is',
      'as',
      'sizeof',
      'alignof',
      'offsetof',
      'struct',
      'impl',
      'trait',
      'where',
      'union',
      'record',
      'data',
      'ref',
      'deref',
      'move',
      'copy',
      'clone',
      'drop',
      'true',
      'false',
      'null',
      'nil',
      'undefined',
      'none',
      'None',
      'Some',
      'Ok',
      'Err',
      'Option',
      'Result',
      'NaN',
      'Infinity',
      'int',
      'float',
      'double',
      'char',
      'bool',
      'string',
      'void',
      'i8',
      'i16',
      'i32',
      'i64',
      'i128',
      'u8',
      'u16',
      'u32',
      'u64',
      'u128',
      'f32',
      'f64',
      'isize',
      'usize',
      'print',
      'println',
      'printf',
      'puts',
      'raise',
      'pass',
      'lambda',
      'with',
      'open',
      'close',
      'read',
      'write',
      'assert',
      'and',
      'or',
      'not',
      'begin',
      'end',
      'rescue',
      'ensure',
      'then',
      'proc',
      'defun',
      'define',
      'letrec',
      'car',
      'cdr',
      'cons',
      'list',
      'quote',
      'select',
      'from',
      'where',
      'group',
      'by',
      'having',
      'order',
      'limit',
      'insert',
      'into',
      'values',
      'update',
      'set',
      'delete',
      'create',
      'table',
      'drop',
      'alter',
      'index',
      'view',
      'join',
      'inner',
      'left',
      'right',
      'on',
      'and',
      'or',
      'not',
      'in',
      'like',
      'between',
    ],

    tokenizer: {
      root: [
        [/^#{1,6}\s+.*$/, 'keyword'],
        [/^```/, { token: 'tag', next: '@codelang' }],
        [/`[^`]*`/, 'string'],
        [/^>\s+.*$/, 'comment.doc'],
        [/^[\*\-\+]\s/, 'tag'],
        [/^\d+\.\s/, 'tag'],
        [/\*{1,3}[^\*]+\*{1,3}/, 'emphasis'],
        [/_{1,3}[^_]+_{1,3}/, 'emphasis'],
        [/~~[^~]+~~/, 'strikethrough'],
        [/\[[^\]]*\]\([^\)]*\)/, 'link'],
        [/!\[[^\]]*\]\([^\)]*\)/, 'tag'],
        [/^[-*_]{3,}\s*$/, 'hr'],
        [/^\|.+\|$/, 'table'],
        [/<\/?[\w\s="/.':;#-\/\?]+>/, 'tag'],
        [/==[^=]+==/, 'mark'],
        [/[a-zA-Z0-9_\-]+/, ''],
        [/./, ''],
      ],

      codelang: [
        [/\S+/, { token: 'type', next: '@codecontent' }],
        [/$/, { token: '', next: '@codecontent' }],
      ],

      codecontent: [
        [/^```/, { token: 'tag', next: '@pop' }],
        [/\/\/.*$/, 'comment'],
        [/#.*$/, 'comment'],
        [/\/\*/, 'comment', '@blockcomment'],
        [/"/, 'string', '@string_double'],
        [/'[^']*'/, 'string'],
        [/`[^`]*`/, 'string'],
        [/\b\d+\.?\d*[fFlLuU]?\b/, 'number'],
        [/0[xX][0-9a-fA-F]+/, 'number.hex'],
        [/0[bB][01]+/, 'number.binary'],
        [/[a-zA-Z_]\w*/, { cases: { '@code_keywords': 'keyword', '@default': '' } }],
        [/[{}()\[\]]/, 'delimiter'],
        [/./, ''],
      ],

      blockcomment: [
        [/[^/*]+/, 'comment'],
        [/\*\//, 'comment', '@pop'],
        [/[/*]/, 'comment'],
      ],

      string_double: [
        [/[^\\"]+/, 'string'],
        [/\\./, 'string.escape'],
        [/"/, 'string', '@pop'],
      ],
    },
  });
}

export function initialize_markdown_support() {
  register_markdown_tokens();

  monaco.languages.registerCompletionItemProvider('markdown', {
    provideCompletionItems: (_model, position) => {
      const word = _model.getWordUntilPosition(position);
      const range = {
        startLineNumber: position.lineNumber,
        endLineNumber: position.lineNumber,
        startColumn: word.startColumn,
        endColumn: word.endColumn,
      };

      const snippets = [
        {
          label: '标题',
          detail: '标题 (Heading)',
          insertText: '# ${1:标题}',
          kind: monaco.languages.CompletionItemKind.Snippet,
        },
        {
          label: 'h2',
          detail: '二级标题 (H2)',
          insertText: '## ${1:标题}',
          kind: monaco.languages.CompletionItemKind.Snippet,
        },
        {
          label: 'h3',
          detail: '三级标题 (H3)',
          insertText: '### ${1:标题}',
          kind: monaco.languages.CompletionItemKind.Snippet,
        },
        {
          label: '粗体',
          detail: '粗体 (Bold)',
          insertText: '**${1:文本}**',
          kind: monaco.languages.CompletionItemKind.Snippet,
        },
        {
          label: '斜体',
          detail: '斜体 (Italic)',
          insertText: '*${1:文本}*',
          kind: monaco.languages.CompletionItemKind.Snippet,
        },
        {
          label: '删除线',
          detail: '删除线 (Strikethrough)',
          insertText: '~~${1:文本}~~',
          kind: monaco.languages.CompletionItemKind.Snippet,
        },
        {
          label: '行内代码',
          detail: '行内代码 (Inline Code)',
          insertText: '`$1`',
          kind: monaco.languages.CompletionItemKind.Snippet,
        },
        {
          label: '代码块',
          detail: '代码块 (Code Block)',
          insertText: '```${1:language}\n$2\n```',
          kind: monaco.languages.CompletionItemKind.Snippet,
        },
        {
          label: '引用',
          detail: '引用 (Blockquote)',
          insertText: '> ${1:引用内容}',
          kind: monaco.languages.CompletionItemKind.Snippet,
        },
        {
          label: '链接',
          detail: '链接 (Link)',
          insertText: '[${1:文本}](${2:url})',
          kind: monaco.languages.CompletionItemKind.Snippet,
        },
        {
          label: '图片',
          detail: '图片 (Image)',
          insertText: '![${1:alt}](${2:url})',
          kind: monaco.languages.CompletionItemKind.Snippet,
        },
        {
          label: '有序列表',
          detail: '有序列表 (Ordered List)',
          insertText: '1. ${1:项目}',
          kind: monaco.languages.CompletionItemKind.Snippet,
        },
        {
          label: '无序列表',
          detail: '无序列表 (Unordered List)',
          insertText: '- ${1:项目}',
          kind: monaco.languages.CompletionItemKind.Snippet,
        },
        {
          label: '任务列表',
          detail: '任务列表 (Task List)',
          insertText: '- [ ] ${1:任务}',
          kind: monaco.languages.CompletionItemKind.Snippet,
        },
        {
          label: '分割线',
          detail: '分割线 (Horizontal Rule)',
          insertText: '---',
          kind: monaco.languages.CompletionItemKind.Snippet,
        },
        {
          label: '表格',
          detail: '表格 (Table)',
          insertText: '| ${1:列1} | ${2:列2} |\n| ${3:-} | ${4:-} |\n| ${5:内容} | ${6:内容} |',
          kind: monaco.languages.CompletionItemKind.Snippet,
        },
      ];

      return {
        suggestions: snippets.map((item) => ({
          label: item.label,
          kind: item.kind,
          detail: item.detail,
          insertText: item.insertText,
          insertTextRules: monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet,
          range,
        })),
      };
    },
  });
}
